# Generated by Django 4.1.6 on 2023-11-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='STATUS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='FIRST_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='LAST_NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
