# Generated by Django 4.1.6 on 2023-11-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0002_userroles_status_alter_userroles_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='IS_LOCKED',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
