# Generated by Django 4.1.6 on 2023-12-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appAUDITAI', '0003_userroles_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='ROLE',
        ),
        migrations.AddField(
            model_name='userroles',
            name='ROLE',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
