# Generated by Django 4.1.6 on 2023-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0004_remove_userroles_role_userroles_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MULTIPLE_COMPANY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MULTIPLE', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MULTIPLE_COMPANY',
                'managed': True,
            },
        ),
    ]
