# Generated by Django 4.1.6 on 2023-12-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0005_multiple_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='COMPANY_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
