# Generated by Django 4.1.6 on 2023-12-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0006_userroles_company_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='COMPANY_ID',
        ),
        migrations.AddField(
            model_name='company',
            name='COMPANY_CODE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='SELECTED',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='COMPANY_NAME',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
