# Generated by Django 4.1.6 on 2023-12-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0008_rename_company_code_company_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='EMAIL_ADDRESS',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='FIRST_NAME',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='LAST_NAME',
        ),
    ]
