# Generated by Django 4.1.6 on 2023-12-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0009_remove_userroles_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='IS_LOCKED',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='ROLE',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='STATUS',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='COMPANY_ID',
        ),
        migrations.AddField(
            model_name='userroles',
            name='COMPANY_ID',
            field=models.ManyToManyField(blank=True, null=True, to='appAUDITAI.company'),
        ),
    ]
