# Generated by Django 4.1.6 on 2023-12-10 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0011_alter_app_list_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='APP_NAME',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list'),
        ),
        migrations.AddField(
            model_name='password',
            name='COMPANY_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.company'),
        ),
        migrations.AlterField(
            model_name='password',
            name='CONTROL_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.controls'),
        ),
    ]
