# Generated by Django 4.1.6 on 2023-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0012_password_app_name_password_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWCONFIGATTACHMENTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='pwconfigs')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
