# Generated by Django 4.1.6 on 2023-12-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0013_pwconfigattachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='COMPANY_ID',
        ),
    ]
