# Generated by Django 4.1.6 on 2023-12-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0014_remove_password_company_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={},
        ),
        migrations.AlterField(
            model_name='password',
            name='COMPLEXITY_ENABLED',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='LOWER',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='MFA_ENABLED',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='NUMBER',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='SPECIAL_CHAR',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='password',
            name='UPPER',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='password',
            table=None,
        ),
    ]
