# Generated by Django 4.1.6 on 2023-12-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0016_pwconfigattachments_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwconfigattachments',
            name='file_name',
            field=models.FileField(null=True, upload_to='pwconfigs/'),
        ),
    ]
