# Generated by Django 4.1.6 on 2023-12-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0017_alter_pwconfigattachments_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PASSWORDPOLICY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPLEXITY_ENABLED', models.BooleanField(default=False)),
                ('LENGTH', models.IntegerField(blank=True, null=True)),
                ('UPPER', models.BooleanField(default=False)),
                ('LOWER', models.BooleanField(default=False)),
                ('NUMBER', models.BooleanField(default=False)),
                ('SPECIAL_CHAR', models.BooleanField(default=False)),
                ('AGE', models.IntegerField(blank=True, null=True)),
                ('HISTORY', models.IntegerField(blank=True, null=True)),
                ('LOCKOUT_ATTEMPT', models.IntegerField(blank=True, null=True)),
                ('LOCKOUT_DURATION', models.CharField(blank=True, max_length=50, null=True)),
                ('MFA_ENABLED', models.BooleanField(default=False)),
                ('COMPANY_ID', models.ManyToManyField(blank=True, null=True, to='appAUDITAI.company')),
            ],
        ),
    ]
