# Generated by Django 4.1.6 on 2023-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0020_password_created_by_password_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TERMINATIONPOLICY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAYS_TO_TERMINATE', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('COMPANY_ID', models.ManyToManyField(blank=True, null=True, to='appAUDITAI.company')),
            ],
        ),
    ]
