# Generated by Django 4.1.6 on 2023-12-22 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0021_terminationpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP_USER_UPLOAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='app_users/')),
                ('activated', models.BooleanField(default=False)),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_record')),
            ],
            options={
                'db_table': 'USER_UPLOAD_ATTACHMENTS',
                'managed': True,
            },
        ),
    ]
