# Generated by Django 4.1.6 on 2023-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0022_app_user_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminationpolicy',
            name='DAYS_TO_TERMINATE',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
