# Generated by Django 4.1.6 on 2024-01-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0024_app_new_user_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_record',
            name='ACCESS_APPROVER_NAME1',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_approver_name1', to='appAUDITAI.hr_record'),
        ),
        migrations.AlterField(
            model_name='app_record',
            name='ACCESS_APPROVER_NAME2',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_approver_name2', to='appAUDITAI.hr_record'),
        ),
        migrations.AlterField(
            model_name='app_record',
            name='ACCESS_APPROVER_TITLE1',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_approver_title1', to='appAUDITAI.hr_record'),
        ),
        migrations.AlterField(
            model_name='app_record',
            name='ACCESS_APPROVER_TITLE2',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='access_approver_title2', to='appAUDITAI.hr_record'),
        ),
        migrations.AlterField(
            model_name='terminationpolicy',
            name='DAYS_TO_TERMINATE',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
