# Generated by Django 4.1.6 on 2024-01-14 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0025_alter_app_record_access_approver_name1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN_ROLES_FILTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CREATED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=50, null=True)),
                ('APP_NAME', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_record')),
                ('ROLE_NAME', models.ManyToManyField(related_name='roles_filter', to='appAUDITAI.app_record')),
            ],
        ),
    ]
