# Generated by Django 4.1.6 on 2024-01-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0026_admin_roles_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_roles_filter',
            name='APP_NAME',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAUDITAI.app_list'),
        ),
    ]
