# Generated by Django 5.0.4 on 2024-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAUDITAI', '0029_passwordconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordconfig',
            name='LOCKOUT_DURATION',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passwordconfig',
            name='SESSION_LENGTH',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
